config/routes.rb
Rechq::Application.routes.draw do
  scope "/:locale" do
    
    devise_for :users

    resources :stakeholder_groups, except: [:show]
    resources :stakeholders, except: [:show]
    
    resources :users do
      member do
        get 'lock'
        get 'unlock'
      end
    end
    
    get 'dashboard' => 'dashboard#index'
    
    get "/facilities/gmap_markers" => 'facilities#gmap_markers'
    get "/facilities/update_gps" => 'facilities#update_gps'
    post "/facilities/update_gps" => 'facilities#update_gps'
        
    resources :softwares

    get "/hardware_followups" => 'hardware_followups#index'

    resources :hardwares do
      resources :hardware_followups, except: [:index, :show]
    end
  
    get "/facility_followups" => 'facility_followups#index'
    
    resources :facilities do
      resources :facility_followups, except: [:index, :show]
    end
    
  end
  
  post "/api_cc/incoming" => 'api_cc#incoming'
  get "/api_cc/import" => 'api_cc#import'
  
  get "/:locale" => 'dashboard#index'
  root :to => 'dashboard#index'
  

end

app/models/software.rb
class Software < ActiveRecord::Base
  has_many :hardwares
  has_many :hardware_followups
  has_many :facilities, through: :hardwares
  has_many :hardware_statuses, through: :hardwares
  
  validates_presence_of :name, :description, :released_on
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :lockable
  
  has_many :facility_followups
  has_many :hardware_followups
  has_and_belongs_to_many :facilities
  
  validates_presence_of :name, :phone

  validates_presence_of :email
  validates_uniqueness_of :email

  validates :password, presence: true, on: :create
  validates :password, confirmation: true

  validates_presence_of :role
  
  validate :has_facility_ids
  
  def has_facility_ids
    if facility_ids.length == 0
      errors.add(:facilitiy_ids, "must have access to at least one facility")
    end
  end
  
  def has_followups?
    (facility_followups.count + hardware_followups.count) > 0
  end
  
  def is_last_admin?
    (role == "admin") and (User.where(role: "admin").count == 1)
  end
  
  def is_destroyable?
    !(has_followups? or is_last_admin?)
  end
  
  def is_lockable?(current_user)
    !(is_last_admin? or id == current_user.id)
  end
  
  def authorized_facilities_ids
    af = []
    facilities.each do |f|
      af += f.children.map(&:id)
    end
    af += facilities.ids
    af
  end
  
  def authorized_facilities_grouped_select_options
    options = []
    facilities.order(:name).each do |r|
      options << [r.name, r.id]
      r.children.order(:name).each do |c|
        options << ["-- #{c.name}", c.id]
      end
    end
    options
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :lock, :unlock]
  load_and_authorize_resource

  # GET /softwares
  # GET /softwares.json
  def index
    @users = User.all
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
  end

  # GET /softwares/new
  def new
    @user = User.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    p = user_params
    if p[:password].blank?
      p.delete(:password)
      p.delete(:password_confirmation)
    end
    
    respond_to do |format|
      if @user.update(p)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def lock
    if @user.is_lockable?(current_user)
      @user.lock_access!
      redirect_to @user, notice: "User locked"
    else
      redirect_to @user, alert: "Cannot lock user"
    end
  end
  
  def unlock
    if @user.is_lockable?(current_user)
      @user.unlock_access!
      redirect_to @user, notice: "User unlocked"
    else
      redirect_to @user, alert: "Cannot unlock user"
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    alert = ""
    alert += "Delete follow ups first. " if @user.has_followups?
    alert += "User is the last Administrator." if @user.is_last_admin?
    
    if alert != ""
      alert = "Cannot delete user. " + alert
      redirect_to @user, alert: alert
    else
      @user.destroy
      redirect_to users_url, notice: "User deleted."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                    :role, :notifications, :phone,
                                    {facility_ids: []})
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def role_options
    [[t('roles.viewer'), "viewer"], [t('roles.field_worker'), "field_worker"], [t('roles.project_manager'), "project_manager"],[t('roles.admin'), "admin"]]
  end
end

app/views/users/_form.html.haml
= bootstrap_form_for(@user, style: :horizontal) do |f|
  = f.text_field :name
  = f.text_field :email
  = f.text_field :phone
  
  = hidden_field_tag "user[facility_ids][]", nil
  %div.form-group
    %label.control-label= t('activerecord.attributes.user.facility_ids')
    - Facility.roots.each do |root|
      %div.checkbox
        %label
          = check_box_tag "user[facility_ids][]", root.id, @user.facility_ids.include?(root.id)
          = root.name

  = f.select :role, options_for_select(role_options, @user.role), include_blank: true
  = f.password_field :password
  = f.password_field :password_confirmation
  = f.form_group do
    = f.check_box :notifications, label: t('activerecord.attributes.user.notifications_long')
  
  = f.form_group do
    = f.submit t('save')
    = link_to t('cancel'), @user.id ? @user : users_path

app/views/users/edit.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-user
				= t('.title')
			
%div.row
	%div.col-md-12
		= render 'form'

app/views/users/index.html.haml
%div.row
  %div.col-md-12
    %div.page-header
      %h1
        %i.fa.fa-users
        = t('.title')
        - if can? :manage, User
          = link_to_icon t('.link_new'), new_user_path, "fa fa-plus", class: "btn btn-success btn-xs"

%div.row
  %div.col-md-12
    %table.table
      %thead
        %tr
          %th= t('activerecord.attributes.user.name')
          %th= t('activerecord.attributes.user.phone')
          %th= t('activerecord.attributes.user.role')
          %th= t('activerecord.attributes.user.notifications')

      - @users.each do |user|
        %tr
          %td{class: user.access_locked? ? "locked-user" : ""}= link_to user.name, user
          %td= user.phone
          %td= t("roles.#{user.role}")
          %td
            %i.fa{class: user.notifications ? "fa-check-square-o" : "fa-square-o"}

app/views/users/new.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-user
				= t('.title')
			
%div.row
	%div.col-md-12
		= render 'form'

app/views/users/show.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-user
				%span{class: @user.access_locked? ? "locked-user" : ""}= @user.name
				- if can? :manage, User
					= link_to_icon t('edit'), edit_user_path(@user), "fa fa-pencil", class: "btn btn-primary btn-xs"
					- if @user.is_destroyable? 
						= link_to_icon t('destroy'), @user, "fa fa-trash-o", class: "btn btn-danger btn-xs", :method => :delete, :data => { :confirm => t('are_you_sure') }
					- if @user.is_lockable?(current_user)
						- if @user.access_locked?
							= link_to_icon t('.unlock'), unlock_user_path(@user), "fa fa-unlock", class: "btn btn-warning btn-xs"
						- else
							= link_to_icon t('.lock'), lock_user_path(@user), "fa fa-lock", class: "btn btn-warning btn-xs"

%div.row
	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-envelope", label: t('activerecord.attributes.user.email'), value: mail_to(@user.email) }
	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-wrench", label: t('activerecord.attributes.user.role'), value: t("roles.#{@user.role}")}
  
	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-phone", label: t('activerecord.attributes.user.phone'), value: @user.phone}
	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-map-marker", label: t('activerecord.attributes.user.facility_ids'), value: @user.facilities.map(&:name).join(", ")}

	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-calendar", label: t('activerecord.attributes.user.last_sign_in_at'), value: @user.last_sign_in_at}
	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-globe", label: t('activerecord.attributes.user.last_sign_in_ip'), value: @user.last_sign_in_ip}

	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-calendar", label: t('activerecord.attributes.user.current_sign_in_at'), value: @user.current_sign_in_at}
	%div.col-md-6= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-globe", label: t('activerecord.attributes.user.current_sign_in_ip'), value: @user.current_sign_in_ip}