config/routes.rb
Rechq::Application.routes.draw do
  scope "/:locale" do
    
    devise_for :users

    resources :stakeholder_groups, except: [:show]
    resources :stakeholders, except: [:show]
    
    resources :users do
      member do
        get 'lock'
        get 'unlock'
      end
    end
    
    get 'dashboard' => 'dashboard#index'
    
    get "/facilities/gmap_markers" => 'facilities#gmap_markers'
    get "/facilities/update_gps" => 'facilities#update_gps'
    post "/facilities/update_gps" => 'facilities#update_gps'
        
    resources :softwares

    get "/hardware_followups" => 'hardware_followups#index'

    resources :hardwares do
      resources :hardware_followups, except: [:index, :show]
    end
  
    get "/facility_followups" => 'facility_followups#index'
    
    resources :facilities do
      resources :facility_followups, except: [:index, :show]
    end
    
  end
  
  post "/api_cc/incoming" => 'api_cc#incoming'
  get "/api_cc/import" => 'api_cc#import'
  
  get "/:locale" => 'dashboard#index'
  root :to => 'dashboard#index'
  

end

app/models/facility_followup.rb
class FacilityFollowup < ActiveRecord::Base
  belongs_to :facility
  belongs_to :user
  validates_presence_of :facility_id, :follow_up_on, :description, :user_id
  
  def self.date_last(facility)
    d = facility.facility_followups.order(follow_up_on: :desc).first
    d ? d.follow_up_on : "N/A"
  end
end

app/controllers/facility_followups_controller.rb
class FacilityFollowupsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    respond_to do |format|
      format.html
      format.json { render json: FacilityFollowupsDatatable.new(view_context, current_user) }
    end
  end
  
  def new
    @facility = Facility.find(params[:facility_id])
    @followup = @facility.facility_followups.build
    authorize! :create, @followup
  end
  
  def edit
    @facility = Facility.find(params[:facility_id])
    @followup = @facility.facility_followups.find(params[:id])
    authorize! :update, @followup
  end
  
  def create
    @facility = Facility.find(params[:facility_id])
    @followup = @facility.facility_followups.build(facility_followup_params)
    authorize! :create, @followup
    
    respond_to do |format|
      if @followup.save
        Notification.facility_followup_email(@followup).deliver
        format.html { redirect_to @facility, notice: 'Facility Follow Up was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end
  
  def update
    @facility = Facility.find(params[:facility_id])
    @followup = @facility.facility_followups.find(params[:id])
    authorize! :update, @followup
    
    respond_to do |format|
      if @followup.update(facility_followup_params)
        format.html { redirect_to @facility, notice: 'Facility Follow Up was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end
  
  def destroy
    @facility = Facility.find(params[:facility_id])
    @follow = FacilityFollowup.find(params[:id])
    authorize! :create, @follow
    @follow.destroy
    redirect_to @facility, notice: "Facility Follow Up successfully destroyed"
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_followup_params
      params.require(:facility_followup).permit(:description, :follow_up_on, :facility_id, :user_id)
    end
end

app/helpers/facility_followups_helper.rb
module FacilityFollowupsHelper
end

app/views/facility_followups/_form.html.haml
= bootstrap_form_for([@facility, @followup], style: :horizontal) do |f|    
  = f.text_field :follow_up_on, class: "datepicker"
  = f.text_area :description, label: t('activerecord.attributes.facility_followup.description_html')
  = f.hidden_field :user_id, value: current_user.id
  = f.form_group do
    = f.submit t('save')
    = link_to t('cancel'), facility_url(@facility)

= render partial: "shared/textile_helper"

app/views/facility_followups/_index.html.haml
%div.row
  %div.col-md-12
    %div.page-header
      %h3
        %i.fa.fa-eye
        = t('.title')
        - if can? :create, FacilityFollowup
          = link_to_icon t('.link_new'), new_facility_facility_followup_path(facility), "fa fa-plus", class: "btn btn-success btn-xs"
        %button.btn.btn-primary.btn-sm.pull-right#ff_list_btn{"data-toggle" => "collapse", "href" => "#ff_list"}
          %i.fa.fa-arrow-circle-up#ff_list_icon
    %div.collapse.in#ff_list
      %table.table.table-striped
        - facility.facility_followups.includes(:user).order(follow_up_on: :desc).each do |ff|
          - action_links = [link_to_icon(t('edit'), edit_facility_facility_followup_path(facility, ff), "fa fa-pencil", class: "btn btn-primary btn-xs"), link_to_icon(t('destroy'), [facility, ff], "fa fa-trash-o", class: "btn btn-danger btn-xs", :method => :delete, :data => { :confirm => t('are_you_sure') })]
          %tr
            %td
              %div.row
                .col-md-3
                  = render partial: "shared/model_property", locals: {bg_color: "alert-warning", icon: "fa-calendar", label: t('activerecord.attributes.facility_followup.follow_up_on'), value: ff.follow_up_on}
                .col-md-3
                  = render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-user", label: t('activerecord.attributes.facility_followup.user_id'), value: ff.user.name}
                .col-md-3
                  - if can? :update, ff
                    = render partial: "shared/action_links", locals: {bg_color: "", icon: "fa-code", label: "", links: action_links}
              %div.row
                .col-md-12= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-info-circle", label: t('activerecord.attributes.facility_followup.description'), value: RedCloth.new(ff.description).to_html, escape_html: true}
          
          

app/views/facility_followups/edit.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				= t('.title')
				%small
					%em= "#{t('for')} #{@facility.name}"

%div.row
	%div.col-md-12
		= render 'form'

app/views/facility_followups/new.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				= t('.title')
				%small
					%em= "#{t('for')} #{@facility.name}"

%div.row
	%div.col-md-12
		= render 'form'