config/routes.rb
Rechq::Application.routes.draw do
  scope "/:locale" do
    
    devise_for :users

    resources :stakeholder_groups, except: [:show]
    resources :stakeholders, except: [:show]
    
    resources :users do
      member do
        get 'lock'
        get 'unlock'
      end
    end
    
    get 'dashboard' => 'dashboard#index'
    
    get "/facilities/gmap_markers" => 'facilities#gmap_markers'
    get "/facilities/update_gps" => 'facilities#update_gps'
    post "/facilities/update_gps" => 'facilities#update_gps'
        
    resources :softwares

    get "/hardware_followups" => 'hardware_followups#index'

    resources :hardwares do
      resources :hardware_followups, except: [:index, :show]
    end
  
    get "/facility_followups" => 'facility_followups#index'
    
    resources :facilities do
      resources :facility_followups, except: [:index, :show]
    end
    
  end
  
  post "/api_cc/incoming" => 'api_cc#incoming'
  get "/api_cc/import" => 'api_cc#import'
  
  get "/:locale" => 'dashboard#index'
  root :to => 'dashboard#index'
  

end

app/models/software.rb
class Software < ActiveRecord::Base
  has_many :hardwares
  has_many :hardware_followups
  has_many :facilities, through: :hardwares
  has_many :hardware_statuses, through: :hardwares
  
  validates_presence_of :name, :description, :released_on
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_software, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /softwares
  # GET /softwares.json
  def index
    @softwares = Software.order(released_on: :desc)
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
  end

  # GET /softwares/new
  def new
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)

    respond_to do |format|
      if @software.save
        format.html { redirect_to @software, notice: 'Software was successfully created.' }
        format.json { render action: 'show', status: :created, location: @software }
      else
        format.html { render action: 'new' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to @software, notice: 'Software was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    alert = ""
    alert += "Update hardwares using this software first. " if @software.hardwares.count > 0
    alert += "Delete hardware followup linked to this software first. " if @software.hardware_followups.count > 0
    
    if alert != ""
      alert = "Cannot delete software. " + alert
      redirect_to @software, alert: alert
    else
      @software.destroy
      redirect_to softwares_url, notice: "Software deleted."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:name, :description, :released_on)
    end
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
  def gmap_facility_markers(software)
    markers = []
    software.facilities.distinct.each do |f|
      markers << "#{f.latitude},#{f.longitude}"
    end
    markers.join('|')
  end
end

app/views/softwares/_datatable_translations.html.haml
%div#datatables_translations
  %span#sLengthMenuF= t('datatables.sLengthMenu', assets: t("datatables.facilities"))
  %span#sLengthMenuH= t('datatables.sLengthMenu', assets: t("datatables.hardwares"))

  %span#sZeroRecordsF= t('datatables.sZeroRecords', asset: t("datatables.facility"))
  %span#sZeroRecordsH= t('datatables.sZeroRecords', asset: t("datatables.hardware"))
  
  %span#sInfo= t('datatables.sInfo')
  
  %span#sInfoEmpty= t('datatables.sInfoEmpty')
  
  %span#sInfoFilteredF= t('datatables.sInfoFiltered', assets: t("datatables.facilities"))
  %span#sInfoFilteredH= t('datatables.sInfoFiltered', assets: t("datatables.hardwares"))
  
  %span#sNext= t('datatables.sNext')
  
  %span#sPrevious= t('datatables.sPrevious')
  
  %span#sSearch= t('datatables.sSearch')

app/views/softwares/_form.html.haml
= bootstrap_form_for(@software, style: :horizontal) do |f|
	= f.text_field :name
	= f.text_area :description, label: t('activerecord.attributes.software.description_html')
	= f.text_field :released_on, class: "datepicker"
	= f.form_group do
		= f.submit t('save')
		= link_to t('cancel'), @software.id ? @software : softwares_path

= render partial: "shared/textile_helper"

app/views/softwares/_hardware_list.html.haml
%div.row
  %div.col-md-12
    %div.page-header
      %h3
        %i.fa.fa-laptop
        = t('.title')
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", href: "#software_hardware_list"}
          = t('.list_hardware')
          %span.badge= software.hardwares.count
      %li
        %a{"data-toggle" => "tab", href: "#software_facilities_list"}
          = t('.list_facilities')
          %span.badge= software.facilities.distinct.count
      %li
        %a{"data-toggle" => "tab", href: "#software_facilities_map"}= t('.map_facilities')
      %li
        %a{"data-toggle" => "tab", href: "#software_status_stats"}= t('.status_statistics')
        
    %div.tab-content
      %div.tab-pane.fade.in.active#software_hardware_list
        %br
        %table.table.table-striped#software_hardware_table
          %thead
            %th
          - software.hardwares.includes(:facility, :hardware_status).each do |hw|
            %tr
              %td
                %div.row
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: "alert-warning", icon: "fa-laptop", label: t('activerecord.attributes.hardware.code'), value: link_to(hw.code, hw)}
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-hospital-o", label: t('activerecord.attributes.hardware.facility_id'), value: hw.facility.name}
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-flag", label: t('activerecord.attributes.hardware.hardware_status_id'), value: t("hardware_status.#{hw.hardware_status.name}")}
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-eye", label: t('last_follow_up'), value: HardwareFollowup.date_last(hw)}

      %div.tab-pane.fade#software_facilities_list
        %br
        %div.well.well-sm= t('.facility_diff_hardware')
        %table.table.table-striped#software_facilities_table
          %thead
            %th
          - software.facilities.distinct.each do |f|
            - count = f.hardwares.count
            - w_count = f.hardwares.where(software_id: software.id).count
            - bg_color = count == w_count ? "alert-warning" : "alert-danger"
            %tr
              %td
                %div.row
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: bg_color, icon: "fa-hospital-o", label: t('activerecord.attributes.hardware.facility_id'), value: link_to(f.name, f)}
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-laptop", label: t('.hardware_with_software'), value: w_count}
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-laptop", label: t('n_hardware'), value: count}
                  .col-md-3= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-eye", label: t('last_follow_up'), value: FacilityFollowup.date_last(f)}
      %div.tab-pane.fade#software_facilities_map
        %br
        %div.row
          .col-md-8.col-md-offset-2.text-center
            = image_tag "http://maps.googleapis.com/maps/api/staticmap?size=500x350&markers=#{gmap_facility_markers(software)}&sensor=false&key=AIzaSyBLEWKx0sXyol82v5OlEO83_75VWl6dpq8", alt: "", class: "img-thumbnail"
      %div.tab-pane.fade#software_status_stats
        %br
        %div.row
          - HardwareStatus.all.order(:id).each do |hws|
            .col-md-3= render partial: "shared/model_property", locals: {bg_color: "status-#{hws.name}", icon: "", label: t("hardware_status.#{hws.name}"), value: software.hardwares.where(hardware_status_id: hws.id).count}
        

app/views/softwares/edit.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-code
				= t('.title')
			
%div.row
	%div.col-md-12
		= render 'form'

app/views/softwares/index.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-code
				= t('.title')
				- if can? :manage, Software
					= link_to_icon t('.link_new'), new_software_path, "fa fa-plus", class: "btn btn-success btn-xs"

%div.row
	%div.col-md-12
		%table.table
			%thead
				%tr
					%th= t('activerecord.attributes.software.name')
					%th= t('activerecord.attributes.software.released_on')
					%th= t('activerecord.attributes.software.description')
					%th= t('n_hardware')

			- @softwares.each do |software|
				%tr
					%td= link_to software.name, software
					%td= software.released_on
					%td!= RedCloth.new(software.description).to_html
					%td= software.hardwares.count

app/views/softwares/new.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-code
				= t('.title')
			
%div.row
	%div.col-md-12
		= render 'form'

app/views/softwares/show.html.haml
%div.row
  %div.col-md-12
    %div.page-header
      %h1
        %i.fa.fa-code
        = @software.name
        - if can? :manage, Software
          = link_to_icon t('edit'), edit_software_path(@software), "fa fa-pencil", class: "btn btn-primary btn-xs"
          = link_to_icon t('destroy'), @software, "fa fa-trash-o", class: "btn btn-danger btn-xs", :method => :delete, :data => { :confirm => t('are_you_sure') }

%div.row
  %div.col-md-6
    = render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-download", label: t('activerecord.attributes.software.released_on'), value: @software.released_on}
  %div.col-md-6
    = render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-info-circle", label: t('activerecord.attributes.software.description'), value: RedCloth.new(@software.description).to_html, escape_html: true}

= render partial: "hardware_list", locals: {software: @software}

= render partial: "datatable_translations"