config/routes.rb
Rechq::Application.routes.draw do
  scope "/:locale" do
    
    devise_for :users

    resources :stakeholder_groups, except: [:show]
    resources :stakeholders, except: [:show]
    
    resources :users do
      member do
        get 'lock'
        get 'unlock'
      end
    end
    
    get 'dashboard' => 'dashboard#index'
    
    get "/facilities/gmap_markers" => 'facilities#gmap_markers'
    get "/facilities/update_gps" => 'facilities#update_gps'
    post "/facilities/update_gps" => 'facilities#update_gps'
        
    resources :softwares

    get "/hardware_followups" => 'hardware_followups#index'

    resources :hardwares do
      resources :hardware_followups, except: [:index, :show]
    end
  
    get "/facility_followups" => 'facility_followups#index'
    
    resources :facilities do
      resources :facility_followups, except: [:index, :show]
    end
    
  end
  
  post "/api_cc/incoming" => 'api_cc#incoming'
  get "/api_cc/import" => 'api_cc#import'
  
  get "/:locale" => 'dashboard#index'
  root :to => 'dashboard#index'
  

end

app/models/hardware.rb
class Hardware < ActiveRecord::Base
  belongs_to :hardware_status
  belongs_to :facility
  belongs_to :software
  has_many :hardware_followups, dependent: :destroy

  validates_presence_of :code, :bought_on, :inventory_on, :hardware_status_id,
                        :brand, :model, :color, :configuration, :kind, :facility_id, :software_id
  
  validates_uniqueness_of :code
end

app/controllers/hardwares_controller.rb
class HardwaresController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_hardware, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /hardwares
  # GET /hardwares.json
  def index
    #@hardwares = Hardware.order(code: :asc)
    respond_to do |format|
      format.html
      format.json { render json: HardwaresDatatable.new(view_context, current_user) }
    end
  end

  # GET /hardwares/1
  # GET /hardwares/1.json
  def show
  end

  # GET /hardwares/new
  def new
    @hardware = Hardware.new
  end

  # GET /hardwares/1/edit
  def edit
  end

  # POST /hardwares
  # POST /hardwares.json
  def create
    @hardware = Hardware.new(hardware_params)

    respond_to do |format|
      if @hardware.save
        format.html { redirect_to @hardware, notice: 'Hardware was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hardware }
      else
        format.html { render action: 'new' }
        format.json { render json: @hardware.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hardwares/1
  # PATCH/PUT /hardwares/1.json
  def update
    respond_to do |format|
      if @hardware.update(hardware_params)
        format.html { redirect_to @hardware, notice: 'Hardware was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hardware.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hardwares/1
  # DELETE /hardwares/1.json
  def destroy
    @hardware.destroy
    respond_to do |format|
      format.html { redirect_to hardwares_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hardware
      @hardware = Hardware.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hardware_params
      params.require(:hardware).permit(:code, :bought_on, :inventory_on, :hardware_status_id, :facility_id, :software_id, :brand, :model, :color, :configuration, :kind)
    end
end

app/helpers/hardwares_helper.rb
module HardwaresHelper
  def translate_hws_options_for_select(options)
    options.each do |o| 
      o[0] = t("hardware_status.#{o[0]}")
    end
  end
end

app/views/hardwares/_form.html.haml
= bootstrap_form_for(@hardware, style: :horizontal) do |f|
	= f.text_field :code
	= f.text_field :bought_on, class: "datepicker"
	= f.text_field :inventory_on, class: "datepicker"
	= f.select :software_id, options_from_collection_for_select(Software.order(released_on: :desc,), :id, :name, @hardware.software_id), include_blank: true
	= f.select :facility_id, options_for_select(current_user.authorized_facilities_grouped_select_options, @hardware.facility_id), include_blank: true
	= f.select :hardware_status_id, options_for_select(translate_hws_options_for_select(HardwareStatus.options_for_select), @hardware.hardware_status_id), include_blank: true
	= f.text_field :brand
	= f.text_field :model
	= f.text_field :color
	= f.text_field :configuration
	= f.text_field :kind
	= f.form_group do
		= f.submit t('save')
		= link_to t('cancel'), @hardware.id ? @hardware : hardwares_path

app/views/hardwares/_hardware_list.html.haml
%br
%table.table#hardware_table{"data-source" => hardwares_url(format: "json")}
  %thead
    %tr
      %th= t('activerecord.attributes.hardware.code')
      %th= t('activerecord.attributes.hardware.facility_id')
      %th= t('activerecord.attributes.hardware.hardware_status_id')
      %th= t('activerecord.attributes.hardware.software_id')
      %th= t('last_follow_up')
  %tbody

app/views/hardwares/_latest_followups.html.haml
%br
%table.table.table-striped#followups_table{"data-source" => hardware_followups_url(format: "json")}
  %thead
    %tr
      %th
  %tbody
    

app/views/hardwares/_latest_followups_item.html.haml
- action_links = [link_to_icon(t('edit'), edit_hardware_hardware_followup_path(ff.hardware, ff), "fa fa-pencil", class: "btn btn-primary btn-xs"), link_to_icon(t('destroy'), [ff.hardware, ff], "fa fa-trash-o", class: "btn btn-danger btn-xs", :method => :delete, :data => { :confirm => t('are_you_sure') })]
%tr
  %td
    %div.row
      .col-md-3
        = render partial: "shared/model_property", locals: {bg_color: "alert-warning", icon: "fa-calendar", label: t('activerecord.attributes.hardware_followup.followup_on'), value: ff.followup_on}
        = render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-user", label: t('activerecord.attributes.hardware_followup.user_id'), value: ff.user_name}
      .col-md-9= render partial: "shared/model_property", locals: {bg_color: "hwf-desc", icon: "fa-info-circle", label: "Description", value: RedCloth.new(ff.description).to_html, escape_html: true}
      .col-md-3= render partial: "shared/model_property", locals: {bg_color: "alert-info", icon: "fa-laptop", label: t('activerecord.attributes.hardware.code'), value: link_to(ff.hardware_code, ff.hardware)}
      .col-md-3= render partial: "shared/model_property", locals: {bg_color: "alert-info", icon: "fa-hospital-o", label: t('activerecord.attributes.hardware.facility_id'), value: ff.facility_name}
      .col-md-3= render partial: "shared/model_property", locals: {bg_color: "alert-info", icon: "fa-flag", label: t('activerecord.attributes.hardware.hardware_status_id'), value: t("hardware_status.#{ff.status_name}")}
      - if can? :manage, ff
        .col-md-3= render partial: "shared/action_links", locals: {bg_color: "", icon: "fa-code", label: "Actions", links: action_links}

app/views/hardwares/edit.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-laptop
				= t('.title')

%div.row
	%div.col-md-12
		= render 'form'

app/views/hardwares/index.html.haml
%div.row
  %div.col-md-12
    %div.page-header
      %h1
        %i.fa.fa-laptop
        = t('.title')
        - if can? :create, Hardware
          = link_to_icon t('.link_new'), new_hardware_path, "fa fa-plus", class: "btn btn-success btn-xs"

%div.row
  %div.col-md-12
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", href: "#hardware_list"}
          = t('.hardware_list')
      %li
        %a{"data-toggle" => "tab", href: "#latest_followups"}
          = t('.latest_followups')
          
    %div.tab-content
      %div.tab-pane.fade.in.active#hardware_list
        = render partial: "hardware_list"

      %div.tab-pane.fade#latest_followups
        = render partial: "latest_followups"

= render partial: "shared/datatables_translations", locals: {asset: t("datatables.hardware"), assets: t("datatables.hardwares"), followup: t("datatables.followup"), followups: t("datatables.followups")}

app/views/hardwares/new.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-laptop
				= t('.title')

%div.row
	%div.col-md-12
		= render 'form'

app/views/hardwares/show.html.haml
%div.row
	%div.col-md-12
		%div.page-header
			%h1
				%i.fa.fa-laptop
				= @hardware.code
				- if can? :manage, Hardware
					= link_to_icon t('edit'), edit_hardware_path(@hardware), "fa fa-pencil", class: "btn btn-primary btn-xs"
					= link_to_icon t('destroy'), @hardware, "fa fa-trash-o", class: "btn btn-danger btn-xs", :method => :delete, :data => { :confirm => t('are_you_sure') }
			
%div.row
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "alert-info", icon: "fa-hospital-o", label: t('activerecord.attributes.hardware.facility_id'), value: @hardware.facility.name}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "alert-info", icon: "fa-flag", label: t('activerecord.attributes.hardware.hardware_status_id'), value: t("hardware_status.#{@hardware.hardware_status.name}")}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "alert-info", icon: "fa-code", label: t('activerecord.attributes.hardware.software_id'), value: @hardware.software.name}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-euro", label: t('activerecord.attributes.hardware.bought_on'), value: @hardware.bought_on}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-apple", label: t('activerecord.attributes.hardware.brand'), value: @hardware.brand}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-square", label: t('activerecord.attributes.hardware.color'), value: @hardware.color}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-file-text", label: t('activerecord.attributes.hardware.inventory_on'), value: @hardware.inventory_on}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-certificate", label: t('activerecord.attributes.hardware.model'), value: @hardware.model}
	%div.col-sm-4
		= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-laptop", label: t('activerecord.attributes.hardware.kind'), value: @hardware.kind}
	%div.col-sm-12
		= render partial: "shared/model_property", locals: {bg_color: "", icon: "fa-info-circle", label: t('activerecord.attributes.hardware.configuration'), value: @hardware.configuration}
					
= render partial: "hardware_followups/index", locals: {hardware: @hardware}